version: "3"

vars: {}
dotenv: [".env"]
env: {}

tasks:
  # 初期環境構築用タスク
  init:
    desc: Initialize project.
    deps:
      - clean
    cmds:
      - task: build
  clean:
    desc: Clean files.
    cmds:
      - cd llama.cpp && git clean -xdf llama.cpp

  build:
    desc: Build llama.cpp.
    dir: llama.cpp
    cmds:
      - make -j4
